name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  unit-tests:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        # node-version: [lts/-1, lts/*, latest]
        node-version: [22, 20]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm update -g npm
      - run: npm install
      - run: npm run build
      - run: npm run test
